install.packages(c("tidyverse","dslabs"))
install.packages("here")
tinytex::install_tinytex()
install.packages("htmlwidgets")
install.packages("pdftools")
install.packages("tidytext")
install.packages("textdata")
install.packages("gutenbergr")
